import { readFile } from "node:fs/promises";
import path from "node:path";
import PDFDocument from "pdfkit";
import { identity, palette, suppliedLogoFiles, useSuppliedLogo } from "@/config/branding";
import type { RecordMetadata } from "@/lib/storage";

/**
 * The patroller's report, rendered as a document worth filing: brand
 * header, occurrence number set large and unambiguous, a details table,
 * the narrative as flowing text, then each photo on its own page. Built
 * entirely in memory — nothing touches disk on the way through.
 *
 * The Nation's logo embeds when useSuppliedLogo is on in config/branding.ts
 * and the asset is present (never generated or approximated); otherwise the
 * dashed placeholder holds the space.
 */

export type ReportPhoto = { buffer: Buffer; contentType: string };

export function canEmbed(contentType: string): boolean {
  return contentType === "image/jpeg" || contentType === "image/png";
}

async function logoBuffer(): Promise<Buffer | null> {
  if (!useSuppliedLogo) return null; // placeholder header; see config/branding.ts
  try {
    return await readFile(path.resolve(`public${suppliedLogoFiles.full}`));
  } catch {
    return null;
  }
}

const PAGE = { w: 612, h: 792, margin: 54 };
const CONTENT_W = PAGE.w - PAGE.margin * 2;

export async function renderReportPdf(input: {
  meta: RecordMetadata;
  narrative?: string;
  photos: ReportPhoto[];
}): Promise<Buffer> {
  const { meta, narrative, photos } = input;
  const logo = await logoBuffer();

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER", margin: PAGE.margin });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const ink = palette.charcoal;
    const muted = palette.gray600;
    const red = palette.red600;

    // --- Header ---
    if (logo) {
      doc.image(logo, PAGE.margin, 44, { fit: [150, 60] });
    } else {
      doc.rect(PAGE.margin, 48, 120, 40).dash(2, { space: 2 }).stroke(palette.gray400).undash();
      doc
        .fontSize(6)
        .fillColor(muted)
        .text(`${identity.nation} logo`, PAGE.margin, 64, { width: 120, align: "center" });
    }

    // Sensitivity, stamped where a reader looks first
    doc
      .fontSize(9)
      .font("Helvetica-Bold")
      .fillColor(meta.sensitivity === "standard" ? muted : red)
      .text(meta.sensitivity.toUpperCase(), PAGE.w - PAGE.margin - 140, 48, {
        width: 140,
        align: "right",
      });
    doc
      .fontSize(8)
      .font("Helvetica")
      .fillColor(muted)
      .text(`${identity.nation} · ${identity.department}`, PAGE.w - PAGE.margin - 220, 62, {
        width: 220,
        align: "right",
      });

    doc.moveTo(PAGE.margin, 112).lineTo(PAGE.w - PAGE.margin, 112).lineWidth(2).stroke(red);

    doc
      .fontSize(16)
      .font("Helvetica-Bold")
      .fillColor(ink)
      .text(meta.recordTypeName, PAGE.margin, 128);
    // Occurrence in a fixed-width face: read over radio, written on paper
    doc.fontSize(15).font("Courier-Bold").fillColor(ink).text(meta.occurrenceNumber, {
      continued: false,
    });

    // --- Details table ---
    const rows: [string, string][] = [
      ["Category", meta.categoryName === "Not applicable" ? "—" : meta.categoryName],
      ["Date of occurrence", meta.recordDate],
      ["Location", meta.locationName === "Not applicable" ? "—" : meta.locationName],
      ["Area", meta.areaName],
      ["Member", meta.authorName],
      ["Submitted by", meta.submittedByName],
      ["Vehicle", meta.vehicleName ?? "—"],
      ["Captured", new Date(meta.capturedAt).toLocaleString("en-CA")],
      ["Filed", new Date(meta.syncedAt).toLocaleString("en-CA")],
      ["Photos", String(photos.length)],
    ];
    let y = doc.y + 14;
    const colLabel = PAGE.margin;
    const colValue = PAGE.margin + 150;
    doc.lineWidth(0.5);
    for (const [label, value] of rows) {
      doc.fontSize(9).font("Helvetica").fillColor(muted).text(label, colLabel, y, { width: 140 });
      doc.fontSize(10).font("Helvetica").fillColor(ink).text(value, colValue, y, {
        width: PAGE.w - PAGE.margin - colValue,
      });
      y = Math.max(doc.y, y + 16) + 4;
      doc
        .moveTo(PAGE.margin, y - 3)
        .lineTo(PAGE.w - PAGE.margin, y - 3)
        .stroke(palette.gray200);
    }

    // --- Narrative ---
    doc.y = y + 10;
    doc.x = PAGE.margin;
    doc.fontSize(11).font("Helvetica-Bold").fillColor(ink).text("Narrative");
    doc.moveDown(0.3);
    doc
      .fontSize(10.5)
      .font("Helvetica")
      .fillColor(ink)
      .text(narrative?.trim() || "No written narrative. See attached photos.", {
        width: CONTENT_W,
        lineGap: 3,
      });

    doc.moveDown(1.5);
    doc
      .fontSize(8)
      .fillColor(muted)
      .text(
        `Generated by ${identity.appName} ${identity.appVersion} · This record is append-only; corrections file a new version.`,
        { width: CONTENT_W },
      );

    // --- Photo pages ---
    photos.forEach((photo, i) => {
      doc.addPage();
      doc
        .fontSize(9)
        .font("Helvetica")
        .fillColor(muted)
        .text(
          `Photo ${i + 1} of ${photos.length} — ${meta.occurrenceNumber}`,
          PAGE.margin,
          40,
        );
      try {
        doc.image(photo.buffer, PAGE.margin, 60, {
          fit: [CONTENT_W, PAGE.h - 130],
          align: "center",
          valign: "center",
        });
      } catch {
        doc
          .fontSize(10)
          .fillColor(muted)
          .text("This photo could not be embedded.", PAGE.margin, 100);
      }
    });

    doc.end();
  });
}

/** Photographed pages only (notebook scans): one page per photo, captioned. */
export function renderPagesPdf(photos: ReportPhoto[], occurrence: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER", margin: 36, autoFirstPage: false });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    photos.forEach((photo, i) => {
      doc.addPage();
      doc
        .fontSize(8)
        .fillColor(palette.gray600)
        .text(`Page ${i + 1} of ${photos.length} — ${occurrence}`, 36, 20);
      doc.image(photo.buffer, 36, 36, { fit: [540, 720], align: "center", valign: "center" });
    });

    doc.end();
  });
}
